### ISSUE TITLE
Directions seem to contradict test requirements

### ISSUE THREAD

**Issue by laarchambault** [learn-co-curriculum/programming-univbasics-3-build-a-calculator-lab#2]
Directions copied from lesson below:

subtraction - Build the method subtraction that subtracts num1 from num2 and returns the result of this calculation

division - Build the method division that divides num1 into num2 and returns the result of this calculation

modulo - Build the method modulo that divides num1 into num2 and gives us the remainder of this calculation

The wording of these three lines make it seem as though the code should be written with num2, then num1, but the tests expect num1, then num2.

For example, the subtraction wording "subtracts num1 from num2", followed directly, should produce "num2 - num1". The test expects "num1 - num2". The same is for the division and modulo.

Also the multiplication wording says "from"....see below.

I recommend changing the wording to this:

subtraction - Build the method subtraction that subtracts num2 from num1 and returns the result of this calculation

multiplication - Build the method multiplication that multiplies num1 and num2 and returns the result of this calculation

division - Build the method division that divides num1 by num2 and returns the result of this calculation

modulo - Build the method modulo that divides num1 by num2 and gives us the remainder of this calculation

**Comment by sgharms** [comment]
Good recommendations. Done!
